<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/03/17 12:28:13

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=s_a',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
